---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - ansible-network.network-engine

  tasks:
    - name: Parse data
      command_parser:
        file: "{{ playbook_dir }}/parser_templates/show_vip_radware.yml"
        content: "{{ lookup('file', './radware.txt') }}"
    
    - name: debug vip_section
      debug: var=vip_section
      when: debug is defined

    - name: debug vport_details
      debug: var=vport_details
      when: debug is defined

    - name: debug radware_vips_facts
      debug: var=radware_vips_facts
      when: debug is defined

    - name: debug vip_facts
      debug: var=vip_facts
      # when: debug is defined

    - copy:
        content: "{{ vip_facts }}"
        dest: radware.yml

    - template:
        src: 'csv.j2'
        dest: "./radware.csv"
